### ISSUE TITLE
pcap_parser::LegacyPcapReader handles short reads poorly.

### ISSUE THREAD

**Issue by vi** [rusticata/pcap-parser#15] opened 2022-02-28 08:58 UTC
Feeding pcap file to the parser slowly and incrementally may lead to `Error: Incomplete read` or endless loop with `PcapError::Incomplete` without syscalls (despite of `reader.refill().unwrap()`).

**Comment by vi** [comment] 2022-02-28 09:11
Swapping the parsing lib do `pcap_file::PcapReader` makes issues go away.

**Comment by chifflier** [comment] 2022-03-08 08:42
Hi,
I'm not sure, but this may be related to 7335348f9d5012089bf329032d716980e06e8865 
A new minor release is due soon (including the above commit).

**Comment by chifflier** [comment] 2022-03-08 09:07
0.13.1 is release, can you confirm if the problem is fixed? If not, can you provide more details and/or some code?
Thanks

**Comment by chifflier** [comment] 2022-05-13 08:08
Closing due to lack of new information.
Bug should be fixed since 0.13.1, please reopen issue if needed.

**Closed by chifflier** 2022-05-13 08:08 UTC
